// Code generated by "stringer -type=ObjectEncoding -trimprefix=ObjectEncoding"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjectEncodingAMF0-0]
	_ = x[ObjectEncodingAMF3-3]
}

const (
	_ObjectEncoding_name_0 = "AMF0"
	_ObjectEncoding_name_1 = "AMF3"
)

func (i ObjectEncoding) String() string {
	switch {
	case i == 0:
		return _ObjectEncoding_name_0
	case i == 3:
		return _ObjectEncoding_name_1
	default:
		return "ObjectEncoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
