// Code generated by "stringer -type=AacPacketType -trimprefix=AacPacketType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AacPacketTypeSequenceHeader-0]
	_ = x[AacPacketTypeRaw-1]
}

const _AacPacketType_name = "SequenceHeaderRaw"

var _AacPacketType_index = [...]uint8{0, 14, 17}

func (i AacPacketType) String() string {
	if i >= AacPacketType(len(_AacPacketType_index)-1) {
		return "AacPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AacPacketType_name[_AacPacketType_index[i]:_AacPacketType_index[i+1]]
}
