// Code generated by "stringer -type=AudioSize -trimprefix=AudioSize"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AudioSize8Bit-0]
	_ = x[AudioSize16Bit-1]
}

const _AudioSize_name = "8Bit16Bit"

var _AudioSize_index = [...]uint8{0, 4, 9}

func (i AudioSize) String() string {
	if i >= AudioSize(len(_AudioSize_index)-1) {
		return "AudioSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioSize_name[_AudioSize_index[i]:_AudioSize_index[i+1]]
}
