// Code generated by "stringer -type=AudioRate -trimprefix=AudioRate -linecomment"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AudioRate5_5kHz-0]
	_ = x[AudioRate11kHz-1]
	_ = x[AudioRate22kHz-2]
	_ = x[AudioRate44kHz-3]
}

const _AudioRate_name = "5.5kHz11kHz22kHz44kHz"

var _AudioRate_index = [...]uint8{0, 6, 11, 16, 21}

func (i AudioRate) String() string {
	if i >= AudioRate(len(_AudioRate_index)-1) {
		return "AudioRate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioRate_name[_AudioRate_index[i]:_AudioRate_index[i+1]]
}
