// Code generated by "stringer -type=AvcPacketType -trimprefix=AvcPacketType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AvcPacketTypeSequenceHeader-0]
	_ = x[AvcPacketTypeNALU-1]
	_ = x[AvcPacketTypeEndOfSequence-2]
}

const _AvcPacketType_name = "SequenceHeaderNALUEndOfSequence"

var _AvcPacketType_index = [...]uint8{0, 14, 18, 31}

func (i AvcPacketType) String() string {
	if i >= AvcPacketType(len(_AvcPacketType_index)-1) {
		return "AvcPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AvcPacketType_name[_AvcPacketType_index[i]:_AvcPacketType_index[i+1]]
}
