// Code generated by "stringer -type=BandwidthLimitType -trimprefix=BandwidthLimit"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BandwidthLimitHard-0]
	_ = x[BandwidthLimitSoft-1]
	_ = x[BandwidthLimitDynamic-2]
}

const _BandwidthLimitType_name = "HardSoftDynamic"

var _BandwidthLimitType_index = [...]uint8{0, 4, 8, 15}

func (i BandwidthLimitType) String() string {
	if i >= BandwidthLimitType(len(_BandwidthLimitType_index)-1) {
		return "BandwidthLimitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BandwidthLimitType_name[_BandwidthLimitType_index[i]:_BandwidthLimitType_index[i+1]]
}
