// Code generated by "stringer -type=ERTMPVideoPacketModExType -trimprefix=ERTMPVideoPacketModExType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPVideoPacketModExTypeTimestampOffsetNano-0]
}

const _ERTMPVideoPacketModExType_name = "TimestampOffsetNano"

var _ERTMPVideoPacketModExType_index = [...]uint8{0, 19}

func (i ERTMPVideoPacketModExType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ERTMPVideoPacketModExType_index)-1 {
		return "ERTMPVideoPacketModExType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERTMPVideoPacketModExType_name[_ERTMPVideoPacketModExType_index[idx]:_ERTMPVideoPacketModExType_index[idx+1]]
}
