// Code generated by "stringer -type=ERTMPAudioPacketType -trimprefix=ERTMPAudioPacketType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAudioPacketTypeSequenceStart-0]
	_ = x[ERTMPAudioPacketTypeCodedFrames-1]
	_ = x[ERTMPAudioPacketTypeSequenceEnd-2]
	_ = x[ERTMPAudioPacketTypeMultichannelConfig-4]
	_ = x[ERTMPAudioPacketTypeMultitrack-5]
	_ = x[ERTMPAudioPacketTypeModEx-7]
}

const (
	_ERTMPAudioPacketType_name_0 = "SequenceStartCodedFramesSequenceEnd"
	_ERTMPAudioPacketType_name_1 = "MultichannelConfigMultitrack"
	_ERTMPAudioPacketType_name_2 = "ModEx"
)

var (
	_ERTMPAudioPacketType_index_0 = [...]uint8{0, 13, 24, 35}
	_ERTMPAudioPacketType_index_1 = [...]uint8{0, 18, 28}
)

func (i ERTMPAudioPacketType) String() string {
	switch {
	case i <= 2:
		return _ERTMPAudioPacketType_name_0[_ERTMPAudioPacketType_index_0[i]:_ERTMPAudioPacketType_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _ERTMPAudioPacketType_name_1[_ERTMPAudioPacketType_index_1[i]:_ERTMPAudioPacketType_index_1[i+1]]
	case i == 7:
		return _ERTMPAudioPacketType_name_2
	default:
		return "ERTMPAudioPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
