// Code generated by "stringer -type=ERTMPAudioChannel -trimprefix=ERTMPAudioChannel"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAudioChannelFrontLeft-0]
	_ = x[ERTMPAudioChannelFrontRight-1]
	_ = x[ERTMPAudioChannelFrontCenter-2]
	_ = x[ERTMPAudioChannelLowFrequency1-3]
	_ = x[ERTMPAudioChannelBackLeft-4]
	_ = x[ERTMPAudioChannelBackRight-5]
	_ = x[ERTMPAudioChannelFrontLeftCenter-6]
	_ = x[ERTMPAudioChannelFrontRightCenter-7]
	_ = x[ERTMPAudioChannelBackCenter-8]
	_ = x[ERTMPAudioChannelSideLeft-9]
	_ = x[ERTMPAudioChannelSideRight-10]
	_ = x[ERTMPAudioChannelTopCenter-11]
	_ = x[ERTMPAudioChannelTopFrontLeft-12]
	_ = x[ERTMPAudioChannelTopFrontCenter-13]
	_ = x[ERTMPAudioChannelTopFrontRight-14]
	_ = x[ERTMPAudioChannelTopBackLeft-15]
	_ = x[ERTMPAudioChannelTopBackCenter-16]
	_ = x[ERTMPAudioChannelTopBackRight-17]
	_ = x[ERTMPAudioChannelLowFrequency2-18]
	_ = x[ERTMPAudioChannelTopSideLeft-19]
	_ = x[ERTMPAudioChannelTopSideRight-20]
	_ = x[ERTMPAudioChannelBottomFrontCenter-21]
	_ = x[ERTMPAudioChannelBottomFrontLeft-22]
	_ = x[ERTMPAudioChannelBottomFrontRight-23]
	_ = x[ERTMPAudioChannelUnused-254]
	_ = x[ERTMPAudioChannelUnknown-255]
}

const (
	_ERTMPAudioChannel_name_0 = "FrontLeftFrontRightFrontCenterLowFrequency1BackLeftBackRightFrontLeftCenterFrontRightCenterBackCenterSideLeftSideRightTopCenterTopFrontLeftTopFrontCenterTopFrontRightTopBackLeftTopBackCenterTopBackRightLowFrequency2TopSideLeftTopSideRightBottomFrontCenterBottomFrontLeftBottomFrontRight"
	_ERTMPAudioChannel_name_1 = "UnusedUnknown"
)

var (
	_ERTMPAudioChannel_index_0 = [...]uint16{0, 9, 19, 30, 43, 51, 60, 75, 91, 101, 109, 118, 127, 139, 153, 166, 177, 190, 202, 215, 226, 238, 255, 270, 286}
	_ERTMPAudioChannel_index_1 = [...]uint8{0, 6, 13}
)

func (i ERTMPAudioChannel) String() string {
	switch {
	case i <= 23:
		return _ERTMPAudioChannel_name_0[_ERTMPAudioChannel_index_0[i]:_ERTMPAudioChannel_index_0[i+1]]
	case 254 <= i && i <= 255:
		i -= 254
		return _ERTMPAudioChannel_name_1[_ERTMPAudioChannel_index_1[i]:_ERTMPAudioChannel_index_1[i+1]]
	default:
		return "ERTMPAudioChannel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
