// Code generated by "stringer -type=ERTMPAudioPacketModExType -trimprefix=ERTMPAudioPacketModExType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAudioPacketModExTypeTimestampOffsetNano-0]
}

const _ERTMPAudioPacketModExType_name = "TimestampOffsetNano"

var _ERTMPAudioPacketModExType_index = [...]uint8{0, 19}

func (i ERTMPAudioPacketModExType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ERTMPAudioPacketModExType_index)-1 {
		return "ERTMPAudioPacketModExType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERTMPAudioPacketModExType_name[_ERTMPAudioPacketModExType_index[idx]:_ERTMPAudioPacketModExType_index[idx+1]]
}
