// Code generated by "stringer -type=ERTMPAvMultitrackType -trimprefix=ERTMPAvMultitrackType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAvMultitrackTypeOneTrack-0]
	_ = x[ERTMPAvMultitrackTypeManyTracks-1]
	_ = x[ERTMPAvMultitrackTypeManyTracksManyCodecs-2]
}

const _ERTMPAvMultitrackType_name = "OneTrackManyTracksManyTracksManyCodecs"

var _ERTMPAvMultitrackType_index = [...]uint8{0, 8, 18, 38}

func (i ERTMPAvMultitrackType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ERTMPAvMultitrackType_index)-1 {
		return "ERTMPAvMultitrackType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERTMPAvMultitrackType_name[_ERTMPAvMultitrackType_index[idx]:_ERTMPAvMultitrackType_index[idx+1]]
}
