// Code generated by "stringer -type=ERTMPAudioChannelOrder -trimprefix=ERTMPAudioChannelOrder"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAudioChannelOrderUnspecified-0]
	_ = x[ERTMPAudioChannelOrderNative-1]
	_ = x[ERTMPAudioChannelOrderCustom-2]
}

const _ERTMPAudioChannelOrder_name = "UnspecifiedNativeCustom"

var _ERTMPAudioChannelOrder_index = [...]uint8{0, 11, 17, 23}

func (i ERTMPAudioChannelOrder) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ERTMPAudioChannelOrder_index)-1 {
		return "ERTMPAudioChannelOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERTMPAudioChannelOrder_name[_ERTMPAudioChannelOrder_index[idx]:_ERTMPAudioChannelOrder_index[idx+1]]
}
