// Code generated by "stringer -type=ERTMPVideoPacketType -trimprefix=ERTMPVideoPacketType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPVideoPacketTypeSequenceStart-0]
	_ = x[ERTMPVideoPacketTypeCodedFrames-1]
	_ = x[ERTMPVideoPacketTypeSequenceEnd-2]
	_ = x[ERTMPVideoPacketTypeCodedFramesX-3]
	_ = x[ERTMPVideoPacketTypeMetadata-4]
	_ = x[ERTMPVideoPacketTypeMPEG2TSSequenceStart-5]
	_ = x[ERTMPVideoPacketTypeMultitrack-6]
	_ = x[ERTMPVideoPacketTypeModEx-7]
}

const _ERTMPVideoPacketType_name = "SequenceStartCodedFramesSequenceEndCodedFramesXMetadataMPEG2TSSequenceStartMultitrackModEx"

var _ERTMPVideoPacketType_index = [...]uint8{0, 13, 24, 35, 47, 55, 75, 85, 90}

func (i ERTMPVideoPacketType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ERTMPVideoPacketType_index)-1 {
		return "ERTMPVideoPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERTMPVideoPacketType_name[_ERTMPVideoPacketType_index[idx]:_ERTMPVideoPacketType_index[idx+1]]
}
