// Code generated by "stringer -type=ERTMPAudioChannelMask -trimprefix=ERTMPAudioChannelMask"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERTMPAudioChannelMaskFrontLeft-1]
	_ = x[ERTMPAudioChannelMaskFrontRight-2]
	_ = x[ERTMPAudioChannelMaskFrontCenter-4]
	_ = x[ERTMPAudioChannelMaskLowFrequency1-8]
	_ = x[ERTMPAudioChannelMaskBackLeft-16]
	_ = x[ERTMPAudioChannelMaskBackRight-32]
	_ = x[ERTMPAudioChannelMaskFrontLeftCenter-64]
	_ = x[ERTMPAudioChannelMaskFrontRightCenter-128]
	_ = x[ERTMPAudioChannelMaskBackCenter-256]
	_ = x[ERTMPAudioChannelMaskSideLeft-512]
	_ = x[ERTMPAudioChannelMaskSideRight-1024]
	_ = x[ERTMPAudioChannelMaskTopCenter-2048]
	_ = x[ERTMPAudioChannelMaskTopFrontLeft-4096]
	_ = x[ERTMPAudioChannelMaskTopFrontCenter-8192]
	_ = x[ERTMPAudioChannelMaskTopFrontRight-16384]
	_ = x[ERTMPAudioChannelMaskTopBackLeft-32768]
	_ = x[ERTMPAudioChannelMaskTopBackCenter-65536]
	_ = x[ERTMPAudioChannelMaskTopBackRight-131072]
	_ = x[ERTMPAudioChannelMaskLowFrequency2-262144]
	_ = x[ERTMPAudioChannelMaskTopSideLeft-524288]
	_ = x[ERTMPAudioChannelMaskTopSideRight-1048576]
	_ = x[ERTMPAudioChannelMaskBottomFrontCenter-2097152]
	_ = x[ERTMPAudioChannelMaskBottomFrontLeft-4194304]
	_ = x[ERTMPAudioChannelMaskBottomFrontRight-8388608]
}

const _ERTMPAudioChannelMask_name = "FrontLeftFrontRightFrontCenterLowFrequency1BackLeftBackRightFrontLeftCenterFrontRightCenterBackCenterSideLeftSideRightTopCenterTopFrontLeftTopFrontCenterTopFrontRightTopBackLeftTopBackCenterTopBackRightLowFrequency2TopSideLeftTopSideRightBottomFrontCenterBottomFrontLeftBottomFrontRight"

var _ERTMPAudioChannelMask_map = map[ERTMPAudioChannelMask]string{
	1:       _ERTMPAudioChannelMask_name[0:9],
	2:       _ERTMPAudioChannelMask_name[9:19],
	4:       _ERTMPAudioChannelMask_name[19:30],
	8:       _ERTMPAudioChannelMask_name[30:43],
	16:      _ERTMPAudioChannelMask_name[43:51],
	32:      _ERTMPAudioChannelMask_name[51:60],
	64:      _ERTMPAudioChannelMask_name[60:75],
	128:     _ERTMPAudioChannelMask_name[75:91],
	256:     _ERTMPAudioChannelMask_name[91:101],
	512:     _ERTMPAudioChannelMask_name[101:109],
	1024:    _ERTMPAudioChannelMask_name[109:118],
	2048:    _ERTMPAudioChannelMask_name[118:127],
	4096:    _ERTMPAudioChannelMask_name[127:139],
	8192:    _ERTMPAudioChannelMask_name[139:153],
	16384:   _ERTMPAudioChannelMask_name[153:166],
	32768:   _ERTMPAudioChannelMask_name[166:177],
	65536:   _ERTMPAudioChannelMask_name[177:190],
	131072:  _ERTMPAudioChannelMask_name[190:202],
	262144:  _ERTMPAudioChannelMask_name[202:215],
	524288:  _ERTMPAudioChannelMask_name[215:226],
	1048576: _ERTMPAudioChannelMask_name[226:238],
	2097152: _ERTMPAudioChannelMask_name[238:255],
	4194304: _ERTMPAudioChannelMask_name[255:270],
	8388608: _ERTMPAudioChannelMask_name[270:286],
}

func (i ERTMPAudioChannelMask) String() string {
	if str, ok := _ERTMPAudioChannelMask_map[i]; ok {
		return str
	}
	return "ERTMPAudioChannelMask(" + strconv.FormatInt(int64(i), 10) + ")"
}
