// Code generated by "stringer -type=SharedObjectEventType -trimprefix=SharedObject"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SharedObjectUse-1]
	_ = x[SharedObjectRelease-2]
	_ = x[SharedObjectRequestChange-3]
	_ = x[SharedObjectChange-4]
	_ = x[SharedObjectSuccess-5]
	_ = x[SharedObjectSendMessage-6]
	_ = x[SharedObjectStatus-7]
	_ = x[SharedObjectClear-8]
	_ = x[SharedObjectRemove-9]
	_ = x[SharedObjectRequestRemove-10]
	_ = x[SharedObjectUseSuccess-11]
}

const _SharedObjectEventType_name = "UseReleaseRequestChangeChangeSuccessSendMessageStatusClearRemoveRequestRemoveUseSuccess"

var _SharedObjectEventType_index = [...]uint8{0, 3, 10, 23, 29, 36, 47, 53, 58, 64, 77, 87}

func (i SharedObjectEventType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_SharedObjectEventType_index)-1 {
		return "SharedObjectEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SharedObjectEventType_name[_SharedObjectEventType_index[idx]:_SharedObjectEventType_index[idx+1]]
}
