// Code generated by "stringer -type=UserControlMessageEvent -trimprefix=UserControl"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserControlStreamBegin-0]
	_ = x[UserControlStreamEOF-1]
	_ = x[UserControlStreamDry-2]
	_ = x[UserControlSetBufferLength-3]
	_ = x[UserControlStreamIsRecorded-4]
	_ = x[UserControlReserved-5]
	_ = x[UserControlPingRequest-6]
	_ = x[UserControlPingResponse-7]
	_ = x[UserControlUDPRequest-8]
	_ = x[UserControlUDPResponse-9]
	_ = x[UserControlBandwidthLimit-10]
	_ = x[UserControlBandwidth-11]
	_ = x[UserControlThrottleBandwidth-12]
	_ = x[UserControlStreamCreated-13]
	_ = x[UserControlStreamDeleted-14]
	_ = x[UserControlSetReadAccess-15]
	_ = x[UserControlSetWriteAccess-16]
	_ = x[UserControlStreamMetaRequest-17]
	_ = x[UserControlStreamMetaResponse-18]
	_ = x[UserControlGetSegmentBoundary-19]
	_ = x[UserControlSetSegmentBoundary-20]
	_ = x[UserControlOnDisconnect-21]
	_ = x[UserControlSetCriticalLink-22]
	_ = x[UserControlDisconnect-23]
	_ = x[UserControlHashUpdate-24]
	_ = x[UserControlHashTimeout-25]
	_ = x[UserControlHashRequest-26]
	_ = x[UserControlHashResponse-27]
	_ = x[UserControlCheckBandwidth-28]
	_ = x[UserControlSetAudioSampleAccess-29]
	_ = x[UserControlSetVideoSampleAccess-30]
	_ = x[UserControlThrottleBegin-31]
	_ = x[UserControlThrottleEnd-32]
	_ = x[UserControlDRMNotify-33]
	_ = x[UserControlRTMFPSync-34]
	_ = x[UserControlQueryIHello-35]
	_ = x[UserControlForwardIHello-36]
	_ = x[UserControlRedirectIHello-37]
	_ = x[UserControlNotifyEOF-38]
	_ = x[UserControlProxyContinue-39]
	_ = x[UserControlProxyRemoveUpstream-40]
	_ = x[UserControlRTMFPSetKeepalives-41]
	_ = x[UserControlSegmentNotFound-46]
}

const (
	_UserControlMessageEvent_name_0 = "StreamBeginStreamEOFStreamDrySetBufferLengthStreamIsRecordedReservedPingRequestPingResponseUDPRequestUDPResponseBandwidthLimitBandwidthThrottleBandwidthStreamCreatedStreamDeletedSetReadAccessSetWriteAccessStreamMetaRequestStreamMetaResponseGetSegmentBoundarySetSegmentBoundaryOnDisconnectSetCriticalLinkDisconnectHashUpdateHashTimeoutHashRequestHashResponseCheckBandwidthSetAudioSampleAccessSetVideoSampleAccessThrottleBeginThrottleEndDRMNotifyRTMFPSyncQueryIHelloForwardIHelloRedirectIHelloNotifyEOFProxyContinueProxyRemoveUpstreamRTMFPSetKeepalives"
	_UserControlMessageEvent_name_1 = "SegmentNotFound"
)

var (
	_UserControlMessageEvent_index_0 = [...]uint16{0, 11, 20, 29, 44, 60, 68, 79, 91, 101, 112, 126, 135, 152, 165, 178, 191, 205, 222, 240, 258, 276, 288, 303, 313, 323, 334, 345, 357, 371, 391, 411, 424, 435, 444, 453, 464, 477, 491, 500, 513, 532, 550}
)

func (i UserControlMessageEvent) String() string {
	switch {
	case i <= 41:
		return _UserControlMessageEvent_name_0[_UserControlMessageEvent_index_0[i]:_UserControlMessageEvent_index_0[i+1]]
	case i == 46:
		return _UserControlMessageEvent_name_1
	default:
		return "UserControlMessageEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
