// Code generated by "stringer -type=VideoCommand -trimprefix=VideoCommand"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VideoCommmandStartSeek-0]
	_ = x[VideoCommandEndSeek-1]
}

const _VideoCommand_name = "VideoCommmandStartSeekEndSeek"

var _VideoCommand_index = [...]uint8{0, 22, 29}

func (i VideoCommand) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoCommand_index)-1 {
		return "VideoCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoCommand_name[_VideoCommand_index[idx]:_VideoCommand_index[idx+1]]
}
