// Code generated by "stringer -type=VideoCodecId -trimprefix=VideoCodecId"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VideoCodecIdReserved0-0]
	_ = x[VideoCodecIdReserved1-1]
	_ = x[VideoCodecIdSorensonH263-2]
	_ = x[VideoCodecIdScreen1-3]
	_ = x[VideoCodecIdOn2VP6-4]
	_ = x[VideoCodecIdOn2VP6Alpha-5]
	_ = x[VideoCodecIdScreen2-6]
	_ = x[VideoCodecIdAvc-7]
	_ = x[VideoCodecIdRealH263-8]
	_ = x[VideoCodecIdMpeg4-9]
	_ = x[VideoCodecIdVP8_ERTMP-1987063864]
	_ = x[VideoCodecIdVP9_ERTMP-1987063865]
	_ = x[VideoCodecIdAV1_ERTMP-1635135537]
	_ = x[VideoCodecIdAvc_ERTMP-1635148593]
	_ = x[VideoCodecIdHevc_ERTMP-1752589105]
	_ = x[VideoCodecIdVVC_ERTMP-1987470129]
}

const (
	_VideoCodecId_name_0 = "Reserved0Reserved1SorensonH263Screen1On2VP6On2VP6AlphaScreen2AvcRealH263Mpeg4"
	_VideoCodecId_name_1 = "AV1_ERTMP"
	_VideoCodecId_name_2 = "Avc_ERTMP"
	_VideoCodecId_name_3 = "Hevc_ERTMP"
	_VideoCodecId_name_4 = "VP8_ERTMPVP9_ERTMP"
	_VideoCodecId_name_5 = "VVC_ERTMP"
)

var (
	_VideoCodecId_index_0 = [...]uint8{0, 9, 18, 30, 37, 43, 54, 61, 64, 72, 77}
	_VideoCodecId_index_4 = [...]uint8{0, 9, 18}
)

func (i VideoCodecId) String() string {
	switch {
	case i <= 9:
		return _VideoCodecId_name_0[_VideoCodecId_index_0[i]:_VideoCodecId_index_0[i+1]]
	case i == 1635135537:
		return _VideoCodecId_name_1
	case i == 1635148593:
		return _VideoCodecId_name_2
	case i == 1752589105:
		return _VideoCodecId_name_3
	case 1987063864 <= i && i <= 1987063865:
		i -= 1987063864
		return _VideoCodecId_name_4[_VideoCodecId_index_4[i]:_VideoCodecId_index_4[i+1]]
	case i == 1987470129:
		return _VideoCodecId_name_5
	default:
		return "VideoCodecId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
