// Code generated by "stringer -type=VideoCodecId -trimprefix=VideoCodecId"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VideoCodecIdReserved0-0]
	_ = x[VideoCodecIdReserved1-1]
	_ = x[VideoCodecIdSorensonH263-2]
	_ = x[VideoCodecIdScreen1-3]
	_ = x[VideoCodecIdOn2VP6-4]
	_ = x[VideoCodecIdOn2VP6Alpha-5]
	_ = x[VideoCodecIdScreen2-6]
	_ = x[VideoCodecIdAvc-7]
	_ = x[VideoCodecIdRealH263-8]
	_ = x[VideoCodecIdMpeg4-9]
}

const _VideoCodecId_name = "Reserved0Reserved1SorensonH263Screen1On2VP6On2VP6AlphaScreen2AvcRealH263Mpeg4"

var _VideoCodecId_index = [...]uint8{0, 9, 18, 30, 37, 43, 54, 61, 64, 72, 77}

func (i VideoCodecId) String() string {
	if i >= VideoCodecId(len(_VideoCodecId_index)-1) {
		return "VideoCodecId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoCodecId_name[_VideoCodecId_index[i]:_VideoCodecId_index[i+1]]
}
