// Code generated by "stringer -type=VideoFrameType -trimprefix=VideoFrameType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VideoFrameTypeInvalid-0]
	_ = x[VideoFrameTypeKeyframe-1]
	_ = x[VideoFrameTypeInterframe-2]
	_ = x[VideoFrameTypeDisposableInterframe-3]
	_ = x[VideoFrameTypeGeneratedKeyframe-4]
	_ = x[VideoFrameTypeVideoInfo-5]
}

const _VideoFrameType_name = "InvalidKeyframeInterframeDisposableInterframeGeneratedKeyframeVideoInfo"

var _VideoFrameType_index = [...]uint8{0, 7, 15, 25, 45, 62, 71}

func (i VideoFrameType) String() string {
	if i >= VideoFrameType(len(_VideoFrameType_index)-1) {
		return "VideoFrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoFrameType_name[_VideoFrameType_index[i]:_VideoFrameType_index[i+1]]
}
