// Code generated by "stringer -type=Type"; DO NOT EDIT.

package amf3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedMarker-0]
	_ = x[ByteArrayMarker-12]
	_ = x[XmlMarker-11]
	_ = x[ObjectMarker-10]
	_ = x[ArrayMarker-9]
	_ = x[DateMarker-8]
	_ = x[XmlDocumentMarker-7]
	_ = x[StringMarker-6]
	_ = x[DoubleMarker-5]
	_ = x[IntegerMarker-4]
	_ = x[TrueMarker-3]
	_ = x[FalseMarker-2]
	_ = x[NullMarker-1]
}

const _Type_name = "UndefinedMarkerNullMarkerFalseMarkerTrueMarkerIntegerMarkerDoubleMarkerStringMarkerXmlDocumentMarkerDateMarkerArrayMarkerObjectMarkerXmlMarkerByteArrayMarker"

var _Type_index = [...]uint8{0, 15, 25, 36, 46, 59, 71, 83, 100, 110, 121, 133, 142, 157}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
