// Code generated by "stringer -type=HeaderType -trimprefix=HeaderType"; DO NOT EDIT.

package chunkstream

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderTypeFull-0]
	_ = x[HeaderTypeSameStream-1]
	_ = x[HeaderTypeSameStreamAndLength-2]
	_ = x[HeaderTypeContinuation-3]
}

const _HeaderType_name = "FullSameStreamSameStreamAndLengthContinuation"

var _HeaderType_index = [...]uint8{0, 4, 14, 33, 45}

func (i HeaderType) String() string {
	if i >= HeaderType(len(_HeaderType_index)-1) {
		return "HeaderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HeaderType_name[_HeaderType_index[i]:_HeaderType_index[i+1]]
}
